// <auto-generated />
using WayOfTheForce.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WayOfTheForce.Web.Migrations
{
    [DbContext(typeof(WayOfTheForceContext))]
    [Migration("20261006061001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WayOfTheForce.Web.Models.Creeds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Affinity")
                        .HasColumnType("int");

                    b.Property<string>("Creed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("TotalHolocrons")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Creeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Affinity = 95,
                            Creed = "Peacekeepers who serve the light side of the Force",
                            CreedName = "Jedi Order",
                            IsFriendly = true,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 2,
                            Affinity = -95,
                            Creed = "Power through passion and mastery of the dark side",
                            CreedName = "Sith Order",
                            IsFriendly = false,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 3,
                            Affinity = 70,
                            Creed = "Freedom and hope against Imperial tyranny",
                            CreedName = "Rebel Alliance",
                            IsFriendly = true,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 4,
                            Affinity = -85,
                            Creed = "Order and control through Imperial rule",
                            CreedName = "Galactic Empire",
                            IsFriendly = false,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 5,
                            Affinity = -55,
                            Creed = "Honor, loyalty, and strength through the warrior creed",
                            CreedName = "Mandalorian Clans",
                            IsFriendly = false,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 6,
                            Affinity = 30,
                            Creed = "Loyalty, courage, and defense of Kashyyyk",
                            CreedName = "Wookiee Clans",
                            IsFriendly = true,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 7,
                            Affinity = -25,
                            Creed = "The Force is a powerful tool, but always loyalty to the Emperor.",
                            CreedName = "Imperial Knights",
                            IsFriendly = false,
                            TotalHolocrons = 0
                        },
                        new
                        {
                            Id = 8,
                            Affinity = 5,
                            Creed = "There is no light without dark. Through passion, we gain strength.",
                            CreedName = "Jeaii Order",
                            IsFriendly = true,
                            TotalHolocrons = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
